FFFF...F...FFFF
======================================================================
FAIL: test_eval_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 71, in test_eval_1
    self.assert_(v == 20)
AssertionError: False is not true

======================================================================
FAIL: test_eval_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 75, in test_eval_2
    self.assert_(v == 125)
AssertionError: False is not true

======================================================================
FAIL: test_eval_3 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 79, in test_eval_3
    self.assert_(v == 89)
AssertionError: False is not true

======================================================================
FAIL: test_eval_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 83, in test_eval_4
    self.assert_(v == 174)
AssertionError: False is not true

======================================================================
FAIL: test_print_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 107, in test_print_4
    self.assert_(w.getvalue() == "900, 1000, 174\n")
AssertionError: False is not true

======================================================================
FAIL: test_solve_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 117, in test_solve_1
    self.assert_(w.getvalue() == "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: False is not true

======================================================================
FAIL: test_solve_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 123, in test_solve_2
    self.assert_(w.getvalue() == "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: False is not true

======================================================================
FAIL: test_solve_3 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 129, in test_solve_3
    self.assert_(w.getvalue() == "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: False is not true

======================================================================
FAIL: test_solve_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 135, in test_solve_4
    self.assert_(w.getvalue() == "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 0.001s

FAILED (failures=9)
TestCollatz.py
